# Generated by Django 3.1.5 on 2021-01-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('entity', models.CharField(max_length=50)),
                ('total_count', models.IntegerField()),
                ('entity_sections', models.CharField(max_length=100)),
                ('organisation_name', models.CharField(max_length=100)),
                ('Doctor_name', models.CharField(max_length=100)),
            ],
        ),
    ]
