# Generated by Django 3.0.4 on 2021-01-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0002_auto_20210107_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataa',
            name='coding_system',
        ),
    ]
