# Generated by Django 3.0.4 on 2021-01-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0003_remove_dataa_coding_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataa',
            old_name='corrected_code_corrected_token',
            new_name='correct_text',
        ),
    ]
