# Generated by Django 3.0.4 on 2021-01-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0004_auto_20210112_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataa',
            old_name='applicable_sections',
            new_name='applicable_for_which',
        ),
    ]
