# Generated by Django 3.0.4 on 2021-01-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0005_auto_20210112_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataa',
            name='recommended_token',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
