# Generated by Django 3.0.4 on 2021-01-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0006_auto_20210112_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_checking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_checking',
            },
        ),
    ]
